"""Tests for style_status.py, the sole producer of style-status.json."""

import json
import os
from pathlib import Path

import style_status
from style_status import (
    REQUIRED_CHECKS,
    SCHEMA_VERSION,
    STATUS_PATH,
    build_payload,
    main,
    parse_record,
    write_status,
)


def _read_status(plugin_dir: Path) -> dict:
    """Load the status file written under `plugin_dir`."""
    return json.loads((plugin_dir / STATUS_PATH).read_text(encoding="utf-8"))


class TestBuildPayload:
    """Tests for the payload shape and the style_clean rule."""

    def test_all_passing_is_clean(self) -> None:
        """Every check ran and passed, so style_clean is true."""
        payload = build_payload(
            {"ruff": "pass", "mypy": "pass", "manifest": "pass"}
        )

        assert payload == {
            "version": SCHEMA_VERSION,
            "style_clean": True,
            "checks": {"ruff": True, "mypy": True, "manifest": True},
        }

    def test_a_failure_is_not_clean(self) -> None:
        """A check that ran and failed makes style_clean false and is named."""
        payload = build_payload(
            {"ruff": "pass", "mypy": "fail", "manifest": "pass"}
        )

        assert payload["style_clean"] is False
        assert payload["checks"]["mypy"] is False

    def test_skipped_check_is_omitted_not_passed(self) -> None:
        """A skipped check is absent from `checks` rather than recorded as true."""
        payload = build_payload(
            {"ruff": "pass", "mypy": "pass", "manifest": "skip"}
        )

        assert "manifest" not in payload["checks"]
        assert payload["style_clean"] is True

    def test_nothing_ran_is_unknown_not_clean(self) -> None:
        """No check ran at all, so style_clean is null rather than vacuously true.

        This is the fail-open case: the toolchain was absent, so the build is
        genuinely unassessed and must not read back as a clean one.
        """
        payload = build_payload(
            {"ruff": "skip", "mypy": "skip", "manifest": "skip"}
        )

        assert payload == {
            "version": SCHEMA_VERSION,
            "style_clean": None,
            "checks": {},
        }

    def test_skipped_required_check_is_unknown(self) -> None:
        """A required check that did not run makes the overall state unknown, even
        when the checks that did run all passed."""
        for skipped in REQUIRED_CHECKS:
            outcomes = dict.fromkeys(("ruff", "mypy", "manifest"), "pass")
            outcomes[skipped] = "skip"

            payload = build_payload(outcomes)

            assert payload["style_clean"] is None, skipped

    def test_skipped_manifest_does_not_make_it_unknown(self) -> None:
        """The manifest check is not required — a plugin without a manifest still
        gets a real verdict."""
        payload = build_payload({"ruff": "pass", "mypy": "fail", "manifest": "skip"})

        assert payload["style_clean"] is False

    def test_carries_a_version(self) -> None:
        """The payload is versioned so a reader can reject an unknown shape."""
        assert build_payload({"ruff": "pass"})["version"] == SCHEMA_VERSION


class TestWriteStatus:
    """Tests for the atomic write."""

    def test_creates_the_artifacts_directory(self, tmp_path: Path) -> None:
        """The .cpa-workflow-artifacts directory is created when absent."""
        write_status(tmp_path, {"version": 1, "style_clean": True, "checks": {}})

        assert (tmp_path / STATUS_PATH).is_file()

    def test_overwrites_invalid_existing_json(self, tmp_path: Path) -> None:
        """A corrupt or truncated status file is replaced wholesale.

        The writer never parses what is already there, so a file left invalid by
        an interrupted run is regenerated by the next check rather than inspected.
        """
        dest = tmp_path / STATUS_PATH
        dest.parent.mkdir(parents=True)
        dest.write_text('{"style_clean": tr', encoding="utf-8")

        write_status(tmp_path, {"version": 1, "style_clean": False, "checks": {}})

        assert _read_status(tmp_path) == {
            "version": 1,
            "style_clean": False,
            "checks": {},
        }

    def test_overwrites_an_older_shape(self, tmp_path: Path) -> None:
        """A payload from a previous schema is replaced, not merged."""
        dest = tmp_path / STATUS_PATH
        dest.parent.mkdir(parents=True)
        dest.write_text('{"style_clean": true, "extra": "gone"}', encoding="utf-8")

        write_status(tmp_path, {"version": 1, "style_clean": True, "checks": {}})

        assert "extra" not in _read_status(tmp_path)

    def test_leaves_no_temporary_file_behind(self, tmp_path: Path) -> None:
        """The tmp file used for the atomic replace is not left in the directory,
        so CPA's `git add` of this directory never picks one up."""
        write_status(tmp_path, {"version": 1, "style_clean": True, "checks": {}})

        assert [path.name for path in (tmp_path / STATUS_PATH.parent).iterdir()] == [
            STATUS_PATH.name
        ]

    def test_ends_with_a_newline(self, tmp_path: Path) -> None:
        """The file is newline-terminated so it reads cleanly in a diff."""
        dest = write_status(tmp_path, {"version": 1, "style_clean": True, "checks": {}})

        assert dest.read_text(encoding="utf-8").endswith("}\n")


class TestParseRecord:
    """Tests for --record argument parsing."""

    def test_parses_pairs_and_defaults_the_rest_to_skip(self) -> None:
        """An unmentioned check defaults to skip, never to pass."""
        assert parse_record(["ruff=pass", "mypy=fail"]) == {
            "ruff": "pass",
            "mypy": "fail",
            "manifest": "skip",
        }

    def test_none_means_nothing_ran(self) -> None:
        """The `none` token records every check as skipped."""
        assert parse_record(["none"]) == {
            "ruff": "skip",
            "mypy": "skip",
            "manifest": "skip",
        }

    def test_rejects_an_unknown_check(self) -> None:
        """A typo'd check name is an error, not a silently ignored pair."""
        try:
            parse_record(["ruffff=pass"])
        except ValueError as exc:
            assert "ruffff" in str(exc)
        else:
            raise AssertionError("expected ValueError")

    def test_rejects_an_unknown_outcome(self) -> None:
        """Only pass/fail/skip are accepted, so `true` cannot mean pass by accident."""
        try:
            parse_record(["ruff=true"])
        except ValueError as exc:
            assert "true" in str(exc)
        else:
            raise AssertionError("expected ValueError")


class TestToolFailureIsNotACheckFailure:
    """Exit 2 means the tool could not run, so the check is skipped not failed."""

    def _stub_runs(self, monkeypatch, ruff, mypy):
        """Make run_checks see the given (returncode, output) pairs."""
        calls = iter([("format", 0, ""), ("ruff", *ruff), ("mypy", *mypy)])

        def fake_run(cmd, cwd, timeout):
            _name, code, out = next(calls)
            return code, out

        monkeypatch.setattr(style_status, "_run", fake_run)

    def test_ruff_exit_2_is_a_skip(self, tmp_path: Path, monkeypatch) -> None:
        """An unparseable ruleset must not be recorded as a plugin style failure.

        It is a platform problem, and `fail` would both misattribute it and,
        upstream in Studio, spend the agent's fix budget on an unfixable error.
        """
        self._stub_runs(monkeypatch, ruff=(2, "ruff failed"), mypy=(0, ""))
        (tmp_path / "mypy.ini").write_text("[mypy]\n")

        outcomes = style_status.run_checks(
            tmp_path, "ruff.toml", str(tmp_path / "mypy.ini")
        )

        assert outcomes["ruff"] == "skip"
        assert style_status.build_payload(outcomes)["style_clean"] is None

    def test_ruff_exit_1_is_a_real_failure(self, tmp_path: Path, monkeypatch) -> None:
        """Diagnostics are what exit 1 means, so they stay a failed check."""
        self._stub_runs(
            monkeypatch, ruff=(1, "handler.py:4:5: D103 ..."), mypy=(0, "")
        )
        (tmp_path / "mypy.ini").write_text("[mypy]\n")

        outcomes = style_status.run_checks(
            tmp_path, "ruff.toml", str(tmp_path / "mypy.ini")
        )

        assert outcomes["ruff"] == "fail"

    def test_mypy_exit_2_is_a_skip(self, tmp_path: Path, monkeypatch) -> None:
        """mypy that could not start has reported nothing about the plugin's types."""
        self._stub_runs(monkeypatch, ruff=(0, ""), mypy=(2, "usage: mypy ..."))
        (tmp_path / "mypy.ini").write_text("[mypy]\n")

        outcomes = style_status.run_checks(
            tmp_path, "ruff.toml", str(tmp_path / "mypy.ini")
        )

        assert outcomes["mypy"] == "skip"

    def test_a_signal_kill_is_a_skip(self, tmp_path: Path, monkeypatch) -> None:
        """A negative code means the tool was killed, not that the plugin is dirty.

        An OOM-kill returns -9, which the documented 0/1/2 contract does not
        cover. Testing the complement of "the tool reported on the code" keeps it
        out of the plugin's record.
        """
        self._stub_runs(monkeypatch, ruff=(-9, ""), mypy=(0, ""))
        (tmp_path / "mypy.ini").write_text("[mypy]\n")

        outcomes = style_status.run_checks(
            tmp_path, "ruff.toml", str(tmp_path / "mypy.ini")
        )

        assert outcomes["ruff"] == "skip"

    def test_an_unknown_exit_code_is_a_skip(self, tmp_path: Path, monkeypatch) -> None:
        """A code above 2 is not a documented diagnostic result, so it is a skip."""
        self._stub_runs(monkeypatch, ruff=(0, ""), mypy=(3, "internal error"))
        (tmp_path / "mypy.ini").write_text("[mypy]\n")

        outcomes = style_status.run_checks(
            tmp_path, "ruff.toml", str(tmp_path / "mypy.ini")
        )

        assert outcomes["mypy"] == "skip"

    def test_mypy_exit_1_is_a_real_failure(self, tmp_path: Path, monkeypatch) -> None:
        """Type errors stay a failed check."""
        self._stub_runs(
            monkeypatch, ruff=(0, ""), mypy=(1, "x.py:2: error: Incompatible ...")
        )
        (tmp_path / "mypy.ini").write_text("[mypy]\n")

        outcomes = style_status.run_checks(
            tmp_path, "ruff.toml", str(tmp_path / "mypy.ini")
        )

        assert outcomes["mypy"] == "fail"


class TestMain:
    """Tests for the command-line entry point."""

    def test_record_writes_the_status(self, tmp_path: Path) -> None:
        """--record emits the payload from the outcomes the caller supplied."""
        exit_code = main(
            ["--record", "ruff=pass", "mypy=fail", "--plugin-dir", str(tmp_path)]
        )

        assert exit_code == 0
        assert _read_status(tmp_path) == {
            "version": SCHEMA_VERSION,
            "style_clean": False,
            "checks": {"ruff": True, "mypy": False},
        }

    def test_record_none_writes_the_unknown_status(self, tmp_path: Path) -> None:
        """--record none records that nothing ran, rather than leaving a stale file.

        This is what the Studio gate writes when its master switch is off, so an
        earlier run's verdict cannot survive as a description of new code.
        """
        (tmp_path / STATUS_PATH).parent.mkdir(parents=True)
        (tmp_path / STATUS_PATH).write_text(
            '{"version": 1, "style_clean": true, "checks": {"ruff": true}}',
            encoding="utf-8",
        )

        exit_code = main(["--record", "none", "--plugin-dir", str(tmp_path)])

        assert exit_code == 0
        assert _read_status(tmp_path) == {
            "version": SCHEMA_VERSION,
            "style_clean": None,
            "checks": {},
        }

    def test_run_without_a_ruff_config_records_unknown(self, tmp_path: Path) -> None:
        """--run against a missing ruleset records the unknown state instead of
        reporting a clean build."""
        exit_code = main(
            [
                "--run",
                "--plugin-dir", str(tmp_path),
                "--ruff-config", str(tmp_path / "absent.toml"),
            ]
        )

        assert exit_code == 0
        assert _read_status(tmp_path)["style_clean"] is None

    def test_rejects_run_without_a_ruff_config_argument(self, tmp_path: Path) -> None:
        """--run needs to be told which ruleset to enforce."""
        assert main(["--run", "--plugin-dir", str(tmp_path)]) == 2

    def test_rejects_a_missing_plugin_dir(self, tmp_path: Path) -> None:
        """A plugin dir that does not exist is a usage error, not a silent no-op."""
        assert main(["--record", "none", "--plugin-dir", str(tmp_path / "nope")]) == 2

    def test_reports_a_write_failure(self, tmp_path: Path) -> None:
        """An unwritable destination exits 2 rather than claiming success."""
        os.chmod(tmp_path, 0o500)
        try:
            exit_code = main(["--record", "none", "--plugin-dir", str(tmp_path)])
        finally:
            os.chmod(tmp_path, 0o700)

        assert exit_code == 2
